export const COLORS = {
  WHITE: '#FFFFFF',
  BLACK: '#000',
  BACKGROUND: '#FFFFFF',
  TRANSPARENT: 'transparent',
  RED: '#EF4F79',
  TEXT_COLOR: '#a6a6a6',
  DARK_TEXT_COLOR: '#484848',
  FADED_TEXT_COLOR: '#8193AE',
  HEADER_COLOR: '#2D79E6',
  SNACK_COLOR: '#63C3A2',
  GREEN: '#56CB8F',
  FOOTER_COLOR: '#FFFFFF',

  BLUE: '#3D8BFF',
  BLUE_TEXT: '#404D66',
  LIGHT_BLUE: '#AAC4F8'
}
