export const COLORS = {
  WHITE: '#FFFFFF',
  BLACK: '#000',
  BACKGROUND: '#FFFFFF',
  TRANSPARENT: 'transparent',
  RED: '#EF4F79',
  TEXT_COLOR: '#a6a6a6',
  DARK_TEXT_COLOR: '#484848',
  FADED_TEXT_COLOR: '#B7B7B7',
  HEADER_COLOR: '#258AE7',
  SNACK_COLOR: '#63C3A2',
  FOOTER_COLOR: '#FFFFFF'
}
